/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeDatabase;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author miphc
 */
public class AddFTE extends javax.swing.JFrame {
    public MyHashTable myHashTable = new MyHashTable();
    FTE fullTime;
    String filename;
    /**
     * Creates new form AddEmployee
     */
    public AddFTE() throws IOException {
        initComponents();
        filename = "src\\main\\java\\EmployeeDatabase\\profile.jpg";
        BufferedImage originalImage = ImageIO.read(new File(filename)); 
        ImageIcon imageIcon = new ImageIcon(originalImage); // load the image to a imageIcon
        Image image1 = imageIcon.getImage(); // transform it 
        Image newimg = image1.getScaledInstance(120, 120,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg); 
        profilePic.setIcon(imageIcon);
        choice2.addItem("Full Time");
        choice2.addItem("Part Time");
        EN.setText("");
        Male.setSelected(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Warning = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        LN = new javax.swing.JTextField();
        EN = new javax.swing.JFormattedTextField();
        Gender = new javax.swing.JLabel();
        D = new javax.swing.JFormattedTextField();
        Location = new javax.swing.JLabel();
        S = new javax.swing.JFormattedTextField();
        L = new javax.swing.JTextField();
        Deductions = new javax.swing.JLabel();
        AddPicture = new javax.swing.JButton();
        profilePic = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Full Time Employee");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Warning.setForeground(new java.awt.Color(190, 0, 0));
        jPanel1.add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add New Employee");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, -1));

        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("Last Name");
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        Salary.setForeground(new java.awt.Color(255, 255, 255));
        Salary.setText("Salary");
        jPanel1.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        EmployeeNumber.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeNumber.setText("Employee ID");
        jPanel1.add(EmployeeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setText("First Name");
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        FN.setBackground(new java.awt.Color(51, 51, 51));
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setBorder(null);
        FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNActionPerformed(evt);
            }
        });
        jPanel1.add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 386, 27));

        LN.setBackground(new java.awt.Color(51, 51, 51));
        LN.setForeground(new java.awt.Color(255, 255, 255));
        LN.setBorder(null);
        LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNActionPerformed(evt);
            }
        });
        jPanel1.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 386, 28));

        EN.setBackground(new java.awt.Color(51, 51, 51));
        EN.setBorder(null);
        EN.setForeground(new java.awt.Color(255, 255, 255));
        EN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        EN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENActionPerformed(evt);
            }
        });
        jPanel1.add(EN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 386, 28));

        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 40, -1));

        D.setBackground(new java.awt.Color(51, 51, 51));
        D.setBorder(null);
        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 386, 26));

        Location.setForeground(new java.awt.Color(255, 255, 255));
        Location.setText("Location");
        jPanel1.add(Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        S.setBackground(new java.awt.Color(51, 51, 51));
        S.setBorder(null);
        S.setForeground(new java.awt.Color(255, 255, 255));
        S.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        jPanel1.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 386, 28));

        L.setBackground(new java.awt.Color(51, 51, 51));
        L.setForeground(new java.awt.Color(255, 255, 255));
        L.setBorder(null);
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel1.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 386, 28));

        Deductions.setForeground(new java.awt.Color(255, 255, 255));
        Deductions.setText("Deductions");
        jPanel1.add(Deductions, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        AddPicture.setBackground(new java.awt.Color(255, 255, 255));
        AddPicture.setIcon(new javax.swing.ImageIcon("C:\\Users\\miphc\\Downloads\\icons8-add-image-24.png")); // NOI18N
        AddPicture.setText("Add Picture");
        AddPicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPictureActionPerformed(evt);
            }
        });
        jPanel1.add(AddPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 30));

        profilePic.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(profilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, 120));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 386, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 386, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 386, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\miphc\\Downloads\\icons8-back-24.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 430));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 390, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 390, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 380, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\miphc\\Downloads\\icons8-save-24.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 160, 30));

        Male.setBackground(new java.awt.Color(51, 51, 51));
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        Female.setBackground(new java.awt.Color(51, 51, 51));
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        jPanel1.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Male");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Female");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\miphc\\Downloads\\icons8-multiply-24.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        choice2.setFocusable(false);
        choice2.setForeground(new java.awt.Color(51, 51, 51));
        choice2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice2ItemStateChanged(evt);
            }
        });
        jPanel1.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPictureActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        try {
            BufferedImage originalImage = ImageIO.read(new File(filename));
            ImageIcon imageIcon = new ImageIcon(originalImage); // load the image to a imageIcon
            Image image1 = imageIcon.getImage(); // transform it
            Image newimg = image1.getScaledInstance(120, 120,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way
            imageIcon = new ImageIcon(newimg);
            profilePic.setIcon(imageIcon);
            //close database connection
            System.out.println("A");
        } catch (Exception ex) {
            Logger.getLogger(EditEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddPictureActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void ENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENActionPerformed

    private void LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNActionPerformed

    private void FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
//            String value= gender.getSelectedItem();
            int g = 0;
//            if("Female".equals(value)){
//                g = 1;
//            }
            if(Female.isSelected()){
                g = 1;
            }
            if(filename.equals("")){
                filename = "src\\main\\java\\EmployeeDatabase\\profile.jpg";
            }
            System.out.println("FILENAME"+filename);
            fullTime = new FTE(Integer.parseInt(EN.getText()), FN.getText(), LN.getText(), g, Integer.parseInt(L.getText()), Double.parseDouble(D.getText()), Double.parseDouble(S.getText()), filename);
            myHashTable.addToTable(fullTime);
            clearFields();
            myHashTable.writeToFile();

            JOptionPane.showMessageDialog(null, "Employee Added", "", JOptionPane.PLAIN_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Enter Valid Values", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        if(Male.isSelected()){
        Female.setSelected(false);
        }
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        if(Female.isSelected()){
        Male.setSelected(false);
        }
    }//GEN-LAST:event_FemaleActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            MainMenu m = new MainMenu();
            m.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(AddFTE.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void choice2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice2ItemStateChanged
        try {
            AddPTE pte = new AddPTE();
            pte.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(AddFTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_choice2ItemStateChanged
    private void clearFields() throws IOException{
        EN.setText("");
        FN.setText("");
        LN.setText("");
        L.setText("");
        D.setText("");
        S.setText("");
        Male.setSelected(true);
        BufferedImage originalImage = ImageIO.read(new File("src\\main\\java\\EmployeeDatabase\\profile.jpg"));
        ImageIcon imageIcon = new ImageIcon(originalImage); // load the image to a imageIcon
        Image image1 = imageIcon.getImage(); // transform it
        Image newimg = image1.getScaledInstance(120, 120,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way
        imageIcon = new ImageIcon(newimg);
        profilePic.setIcon(imageIcon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddFTE().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AddFTE.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPicture;
    private javax.swing.JFormattedTextField D;
    private javax.swing.JLabel Deductions;
    private javax.swing.JFormattedTextField EN;
    private javax.swing.JLabel EmployeeNumber;
    private javax.swing.JTextField FN;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField L;
    private javax.swing.JTextField LN;
    private javax.swing.JLabel Location;
    private javax.swing.JRadioButton Male;
    private javax.swing.JFormattedTextField S;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel Warning;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Choice choice2;
    private javax.swing.JLabel firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel profilePic;
    // End of variables declaration//GEN-END:variables
}
