/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeDatabase;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author miphc
 */
public class Edit extends javax.swing.JFrame {
    MyHashTable table = new MyHashTable();
    public static boolean check = false;
    public static int editing = 0;
    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        Action action = new AbstractAction(){
    @Override
    public void actionPerformed(ActionEvent e)
    {
        editEmp();
    }
};
                editText.addActionListener(action);
        invis();
    }
      public void invis(){
     homeSep.setVisible(false);
     addSep.setVisible(false);
     editSep.setVisible(false);
     removeSep.setVisible(false);
     settingSep.setVisible(false);   
    homeSep.setForeground(Color.white.brighter()); // top line color
    homeSep.setBackground(Color.white.brighter());
    addSep.setForeground(Color.white.brighter()); // top line color
    addSep.setBackground(Color.white.brighter());
    editSep.setForeground(Color.white.brighter()); // top line color
    editSep.setBackground(Color.white.brighter());
    removeSep.setForeground(Color.white.brighter()); // top line color
    removeSep.setBackground(Color.white.brighter());
    settingSep.setForeground(Color.white.brighter()); // top line color
    settingSep.setBackground(Color.white.brighter());  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        editText = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        editLabel = new javax.swing.JLabel();
        editSep = new javax.swing.JSeparator();
        removeSep = new javax.swing.JSeparator();
        Home = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        settingSep = new javax.swing.JSeparator();
        removeLabel = new javax.swing.JLabel();
        homeSep = new javax.swing.JSeparator();
        addLabel = new javax.swing.JLabel();
        addSep = new javax.swing.JSeparator();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-24.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 100, -1));

        editText.setBackground(new java.awt.Color(51, 51, 51));
        editText.setBorder(null);
        editText.setForeground(new java.awt.Color(255, 255, 255));
        editText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Employee Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 180, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-24.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        editLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-24 (2).png"))); // NOI18N
        editLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editLabelMouseExited(evt);
            }
        });
        jPanel2.add(editLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 169, -1, -1));

        editSep.setOpaque(true);
        jPanel2.add(editSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 199, 24, -1));

        removeSep.setOpaque(true);
        jPanel2.add(removeSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 254, 24, -1));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-24.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 59, -1, -1));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-view-26.png"))); // NOI18N
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });
        jPanel2.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 279, -1, -1));

        settingSep.setOpaque(true);
        jPanel2.add(settingSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 309, 24, -1));

        removeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-remove-24 (1).png"))); // NOI18N
        removeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeLabelMouseExited(evt);
            }
        });
        jPanel2.add(removeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 224, -1, -1));

        homeSep.setForeground(new java.awt.Color(255, 255, 255));
        homeSep.setOpaque(true);
        jPanel2.add(homeSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 89, 24, -1));

        addLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-24.png"))); // NOI18N
        addLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addLabelMouseExited(evt);
            }
        });
        jPanel2.add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, -1, -1));

        addSep.setForeground(new java.awt.Color(255, 255, 255));
        addSep.setOpaque(true);
        jPanel2.add(addSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 144, 24, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 340));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-multiply-24.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void editEmp(){
     if(!editText.getText().equals("")){
            try{
                EmployeeInfo temp = table.getFromTable(Integer.parseInt(editText.getText()));
                if(temp instanceof FTE){
                    editing = Integer.parseInt(editText.getText());
                    check = true;
                    MyHashTable.fullOrPart = true;
                    EditEmployee fte = new EditEmployee();
                    fte.setVisible(true);
                    this.dispose();
                }
                else{
                    editing = Integer.parseInt(editText.getText());
                    check = true;
                    MyHashTable.fullOrPart = false;
                    EditEmployee pte = new EditEmployee();
                    pte.setVisible(true);
                    this.dispose();
                }
            }catch(Exception e){
                 Error i = new Error();
            i.setVisible(true);
             
            }
        }else{
        
           Error i = new Error();
            i.setVisible(true);
        }}
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       editEmp();
    }//GEN-LAST:event_editActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            MainMenu main = new MainMenu();
            main.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
          
           Error i = new Error();
            i.setVisible(true);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void editLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLabelMouseClicked
        Edit e = new Edit();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editLabelMouseClicked

    private void editLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLabelMouseEntered
        editSep.setVisible(true);
    }//GEN-LAST:event_editLabelMouseEntered

    private void editLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLabelMouseExited
        editSep.setVisible(false);
    }//GEN-LAST:event_editLabelMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        try {
            MainMenu m = new MainMenu();
            m.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        homeSep.setVisible(true);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        homeSep.setVisible(false);
    }//GEN-LAST:event_HomeMouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        settingSep.setVisible(true);
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        settingSep.setVisible(false);
    }//GEN-LAST:event_settingMouseExited

    private void removeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeLabelMouseClicked
        Remove r = new Remove();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeLabelMouseClicked

    private void removeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeLabelMouseEntered
        removeSep.setVisible(true);
    }//GEN-LAST:event_removeLabelMouseEntered

    private void removeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeLabelMouseExited
        removeSep.setVisible(false);
    }//GEN-LAST:event_removeLabelMouseExited

    private void addLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLabelMouseClicked
        try {
            AddEmployee f = new AddEmployee();
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addLabelMouseClicked

    private void addLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLabelMouseEntered
        addSep.setVisible(true);
    }//GEN-LAST:event_addLabelMouseEntered

    private void addLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLabelMouseExited
        addSep.setVisible(false);
    }//GEN-LAST:event_addLabelMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(Color.red);
        close.setOpaque(true);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(51,51,51));
        close.setOpaque(true);
    }//GEN-LAST:event_closeMouseExited

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
               Display d = new Display();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel addLabel;
    private javax.swing.JSeparator addSep;
    private javax.swing.JLabel close;
    private javax.swing.JButton edit;
    private javax.swing.JLabel editLabel;
    private javax.swing.JSeparator editSep;
    private javax.swing.JFormattedTextField editText;
    private javax.swing.JSeparator homeSep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel removeLabel;
    private javax.swing.JSeparator removeSep;
    private javax.swing.JLabel setting;
    private javax.swing.JSeparator settingSep;
    // End of variables declaration//GEN-END:variables
}
